
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}


###

GET http://localhost:8080/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiYWRtaW4iLCJpc19hZG1pbiI6MSwiaWF0IjoxNjgyNDU2NDI4LCJleHAiOjE2ODI0NTczMjh9.xjmmIb7W2zENxnlhakfQskG_muNo2lE8d074YUE7syc

###

DELETE http://localhost:8080/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiYWRtaW4iLCJpc19hZG1pbiI6MSwiaWF0IjoxNjgyNDQ1NTMyLCJleHAiOjE2ODI0NDY0MzJ9.MO7UugqmfC4X2IX6PiL-_e5Ht0rTAdn3JfUfaBMJlhc"
}
