
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}


###

GET http://localhost:8080/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJiJDEwJC9SVnlLUGdRLjU0YmhwVU9xZFBzZnV3OXAyMTY4TDNmWDY4SjJIMHYvMVEzbmNGcUt3S1NHIiwiaXNfYWRtaW4iOjEsImlhdCI6MTY4MjUxMjQwMiwiZXhwIjoxNjgyNTEzMzAyfQ.OzADpZWxPYQuZyFSIGwCOFa1M3dzyIHGkXNIVO6pxek


###

DELETE http://localhost:8080/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiYWRtaW4iLCJpc19hZG1pbiI6MSwiaWF0IjoxNjgyNDQ1NTMyLCJleHAiOjE2ODI0NDY0MzJ9.MO7UugqmfC4X2IX6PiL-_e5Ht0rTAdn3JfUfaBMJlhc"
}


###